/**
 *
 * $Id$
 */
package ahp.validation;

import ahp.Alternative;
import ahp.Criterion;
import ahp.Goal;
import ahp.Inconsistency;
import ahp.Judgment;
import ahp.Priority;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ahp.Hierarchy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HierarchyValidator {
	boolean validate();

	boolean validateGoal(Goal value);
	boolean validateCriteria(EList<Criterion> value);
	boolean validateAlternatives(EList<Alternative> value);
	boolean validateJudgments(EList<Judgment<?>> value);
	boolean validatePriorities(EList<Priority> value);
	boolean validateInconsistencies(EList<Inconsistency> value);
}
