/**
 *
 * $Id$
 */
package ahp.validation;

import ahp.Hierarchy;

/**
 * A sample validator interface for {@link ahp.Judgment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JudgmentValidator {
	boolean validate();

	boolean validateHierarchy(Hierarchy value);
	boolean validateFirst(Object value);
	boolean validateSecond(Object value);
	boolean validateWeight(int value);
}
